<?php

namespace App\Filament\Admin\Resources\MerchantResource\Pages;

use App\Filament\Admin\Resources\MerchantResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateMerchant extends CreateRecord
{
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['name'] = \Str::slug($data['name']);
        $data['phone'] = str_replace(' ', '', ltrim($data['phone'], '0'));
        $data['email'] = strtolower($data['email']);
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

    protected function handleRecordCreation(array $data): Model
    {
        $data['verified'] = true;
        $data['active'] = true;
        $model = static::getModel()::create(\Arr::except($data, array_keys(config('app.locales'))));
        $model->details()->create(\Arr::only($data, array_keys(config('app.locales'))));
        return $model;
    }

    protected static string $resource = MerchantResource::class;
}
