<?php

namespace App\Filament\Admin\Resources\MerchantResource\Pages;

use App\Filament\Admin\Resources\MerchantResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;

class EditMerchant extends EditRecord
{
    protected static string $resource = MerchantResource::class;

    protected function mutateFormDataBeforeSave(array $data): array
    {
        $data['name'] = \Str::slug($data['name']);
        $data['phone'] = str_replace(' ', '', ltrim($data['phone'], '0'));
        $data['email'] = strtolower($data['email']);
        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }

    protected function handleRecordUpdate(Model $record, array $data): Model
    {
        $record->update(\Arr::except($data, array_keys(config('app.locales'))));
        $details = \Arr::only($data, array_keys(config('app.locales')));
        if (!$record->details()->exists())
            $record->details()->create($details);
        $record->details->update($details);
        return $record;
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }
}
